/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    // String t is generated by random shuffling string s 
    //and then add one more letter at a random position.

//Return the letter that was added to t.
    // sorting
    let st = s.split('').sort();
    let tt = t.split('').sort(); 
    console.log('s:::',st);
    for(let i = 0; i< tt.length; i++){
        if(st[i] != tt[i]){
            return tt[i]
        }
    }
    return -1;
};
