/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    // String t is generated by random shuffling string s 
    //and then add one more letter at a random position.

//Return the letter that was added to t.
    // hashmap 
    // first put every char of s in a map
    // iterate t,
    // whenever a match found, decrease count of that char
    
    
    let sMap = new Map();
    for(let st of s){
        if(sMap.has(st)){
            sMap.set(st, sMap.get(st)+1)
        }
        else sMap.set(st, 1);
    }
    
    for(let tStr of t){
        if(sMap.has(tStr)){
            let charCount = sMap.get(tStr);
            if(charCount == 0){
                return tStr;
            }
            else{
                sMap.set(tStr, charCount-1);
            }
        }
        else return tStr;
    }
    return -1;
};
